---

- name: Change BIG-IP admin password
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ SSH_KEY_PATH }}"
      transport: cli
      user: admin
    commands: modify auth user admin password {{ ADMIN_PASSWORD }}
  delegate_to: localhost