---

  
- name: Set BIG-IP admin password
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "/.ssh/id_rsa"
      transport: cli
      user: azureuser
    commands: modify auth user azureuser password {{ ADMIN_PASSWORD | regex_replace('!', '\!') | regex_escape('posix_basic') }}
  delegate_to: localhost

- name: enable iApps LX Package management in UI
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "/.ssh/id_rsa"
      transport: cli
      user: azureuser
    commands: run /util bash -c "touch /var/config/rest/iapps/enable"
  delegate_to: localhost